### ISSUE TITLE
Nginx logs?

### ISSUE THREAD

**Issue by julj** [tiangolo/uwsgi-nginx-docker#1]
Hi, thanks for this image!
I could not see nginx logs. In my case they are redirected to stdout and stderr by default, so they should be visible in docker logs, but they are not. It seems to be an issue with supervisor: http://veithen.github.io/2015/01/08/supervisord-redirecting-stdout.html.
Adding the following to supervisord.conf works in my case:

```
[program:nginx]
(...)
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

**Comment by tiangolo** [comment]
I just added it to both Nginx and uWSGI in supervisord.conf

(and it is included in the latest build in Docker Hub)

Thank you!
