### ISSUE TITLE
Python 3.8-alpine 3.12

### ISSUE THREAD

**Issue by williamgorgor** [tiangolo/uwsgi-nginx-docker#102]
Hi,

Please plan to update Alpine version of 3.12 or above on Python 3.8. Some of the python module are getting not supported to Alpine 3.11. Thank you very much.

**Comment by tiangolo** [comment]
Thanks! This should be solved in https://github.com/tiangolo/uwsgi-nginx-docker/pull/148 by @haley-comet :tada:

The new images have just been pushed. :rocket:
