### ISSUE TITLE
Information Disclosure Vulnerability in NGINX 1.21.1

### ISSUE THREAD

**Issue by cometa-haley** [tiangolo/uwsgi-nginx-docker#146]
While running a security scan we found out this image presents an Information Disclosure Vulnerability rated as high level issue (see https://trac.nginx.org/nginx/ticket/376).

Is this repo currently being maintained (would a PR be reviewed if submitted) or should we look for an alternative?

Thank you very much for your work!

**Comment by tiangolo** [comment]
Thanks for the report and the PR! :bow: :cake:
