### ISSUE TITLE
Why doesn't this Dockerfile simply run `apt install nginx`?

### ISSUE THREAD

**Issue by papb** [tiangolo/uwsgi-nginx-docker#151]
Hello, I am trying to customize this Dockerfile and for that I have to understand how it works, and I noticed you had the trouble of writing [install-nginx-debian.sh](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/docker-images/install-nginx-debian.sh) which has a lot of commands...

Is there any reason for not simply running `apt install nginx`?

For example, it seems to be done by `phusion/passenger-docker` [here](https://github.com/phusion/passenger-docker/blob/62b7e329db8d9c225d3b5cbb26df34589abd7c4a/image/nginx-passenger.sh#L23).

Thank you very much! This has been a huge help!

**Comment by fegmorte** [comment]
Hello @papb 
I also use this image for our project.
If you have to the shell script you will line 68:
```    
&& apt-get install --no-install-recommends --no-install-suggests -y \
                        $nginxPackages \
```
He finally just installs the nginx package.

Lots of things are done before that command like installing the GPG KEY, checking if it exists, checking the architecture and so on ... And as he said at the beginning of the script, all the commands come from the official nginx docker images.

**Comment by papb** [comment]
Thanks! After reading your commend and looking again to the source code, I think I'd answer myself as follows:

Apart from `apt install nginx`, it is:

- Also installing [a few other packages](https://github.com/tiangolo/uwsgi-nginx-docker/blob/984c9457e0fb63140b09b2cd0bd68a878b72518c/docker-images/install-nginx-debian.sh#L30-L34)
- Adapting gpg keys and other things for non-`amd64|i386|arm64` architectures
- Cleaning up leftovers

Thank you @fegmorte !
