### ISSUE TITLE
Missing nginx.conf

### ISSUE THREAD

**Issue by mr-sk** [tiangolo/uwsgi-nginx-docker#18]
The root of this project doesn't have an nginx.conf file. 

So the Dockerfile command: `COPY nginx.conf /etc/nginx/conf.d/` fails. 
`COPY failed: stat /var/lib/docker/tmp/docker-builder489751094/nginx.conf: no such file or directory`

**Comment by tiangolo** [comment]
This issue seems to be closed. Did you solve your problems?
