### ISSUE TITLE
Changing `worker_processes` value in nginx configuration

### ISSUE THREAD

**Issue by naktinis** [tiangolo/uwsgi-nginx-docker#21]
In the default `/etc/nginx/nginx.conf` `worker_processes` is set to 1. However, I'd like to change this value.

I would suggest one of these approaches:

1. set the value to `auto` (so it is set to the number of CPU cores)
2. create an ENV variable `NGINX_WORKER_PROCESSES` (which can be set in Dockerfiles) and which is written into the config.

**Comment by tiangolo** [comment]
Good idea!

I like the 2 option.

That way the `NGINX_WORKER_PROCESSES` env var could be set to `auto` and it would achieve the same as the option 1.

Do you want to create a Pull Request?

**Comment by naktinis** [comment]
Yes, I think I could create a PR.

What approach would you prefer for setting the value in the configuration? Should I store a modified `/etc/nginx/nginx.conf` based on the nginx default and then copy it to the image, or replace the specific line using `sed` (which is what I'm doing at the moment)? Also, let me know if you have other ideas.

**Comment by tiangolo** [comment]
I think we could set a `NGINX_WORKER_PROCESSES` to be the default (1) in the `Dockerfile`.

Then read that in the `entrypoint.sh` and write an additional config file like `/etc/nginx/conf.d/worker_processes.conf`

Very much in the same way it's done for `NGINX_MAX_UPLOAD`.

Here in the `Dockerfile`: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/Dockerfile#L124

And here in the `entrypoint.sh`: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/entrypoint.sh#L5

**Comment by naktinis** [comment]
I thik `client_max_body_size` parameter can be set like this, because its context is [defined](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) as `http, server, location`. However, `worker_processes` [context is](http://nginx.org/en/docs/ngx_core_module.html#worker_processes) `main`.

Files like `/etc/nginx/conf.d/worker_processes.conf` are imported into the `http` context (see the `include /etc/nginx/conf.d/*.conf;` directive in `/etc/nginx/nginx.conf`). You will not be able to set `worker_processes` there as you'll get the `"worker_processes" directive is not allowed here` error.

Also, you can not simply append a line to `/etc/nginx/nginx.conf`, because the value will then be defined twice and you'll get the `"worker_processes" directive is duplicate` error.

**Comment by tiangolo** [comment]
Yep. You're right. We would have to `sed` it. Like with `USE_LISTEN_PORT` but in the main `nginx.conf`.

**Comment by naktinis** [comment]
Created a pull request (https://github.com/tiangolo/uwsgi-nginx-docker/pull/22). Let me know what you think.

**Comment by naktinis** [comment]
Any updates on this?

**Comment by tiangolo** [comment]
Thanks! Great work. Your PR is merged :tada: .
