### ISSUE TITLE
程序正常运行一段时间，就莫名出现 504 Gateway timeout

### ISSUE THREAD

**Issue by smalldu** [tiangolo/uwsgi-nginx-docker#27]
这个跟nginx配置有关系吗。怎么保证他的稳定性,我怎么查看docker中nginx的日志

**Comment by tiangolo** [comment]
I'm sorry, I don't speak Mandarin. I "google translated" it, and I see you are having 504 Gateway timeout errors. It's possible that your app code has a bug somewhere and breaks. But Nginx keeps trying to speak to uWSGI and waits for it to answer. And then it shows the timeout error. But it's probable that the code actually had an error before at some point.

To see the logs you can use `docker logs` commands: https://docs.docker.com/engine/reference/commandline/logs/
