### ISSUE TITLE
global uwsgi.ini from this docker overwrites custom properties of the app

### ISSUE THREAD

**Issue by felixmaximilian** [tiangolo/uwsgi-nginx-docker#3]
I cannot overwrite all properties that are set in uwsgi-nginx-docker/python2.7/uwsgi.ini  within my own uwsgi.ini, because in the  supervisord.conf the order of loading the init files is "wrong". What other implications would it have to change the order to this:
`
command=/usr/local/bin/uwsgi --ini /etc/uwsgi/uwsgi.ini --ini /app/uwsgi.ini 
`
?

**Comment by tiangolo** [comment]
Good catch. It should work now. Please check and tell me.

**Comment by tiangolo** [comment]
As this was some time ago, I will assume it actually worked and close this issue.

**Comment by felixmaximilian** [comment]
Yes , it worked well. Thank you!
Sebastián Ramírez <notifications@github.com> schrieb am Fr. 30. Dez. 2016
um 23:29:
