### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by Rydgel** [tiangolo/uwsgi-nginx-docker#31]
Would be great to have a Python 3.7 version of this Docker.
Thanks for the nice project :)

**Comment by gaffney** [comment]
+1 prease ;) The Docker should be good to go - [3.7/stretch/Dockerfile](https://github.com/docker-library/python/blob/master/3.7/stretch/Dockerfile)

**Comment by Skwal** [comment]
Any update on this? I would love to see 3.7 too

**Comment by tiangolo** [comment]
Hey guys, Python 3.7 is available now! :tada: 

Thanks to @desaintmartin in PR #39 

I'll close this issue now, but feel free to write more comments here and let me know if there's anything missing.

**Comment by desaintmartin** [comment]
Actually, you did the tedious part. :)

**Comment by tiangolo** [comment]
Hehehe :smile:
