### ISSUE TITLE
Support for additional supervisor programs

### ISSUE THREAD

**Issue by guygriffiths** [tiangolo/uwsgi-nginx-docker#32]
I'm currently looking into running your flask image (https://github.com/tiangolo/uwsgi-nginx-flask-docker) which is extended from this one.  However, I would like to run an instance of celery (http://www.celeryproject.org/) within the same container (since it needs access to many of the same modules I define in my flask app).

I can do this by extending from your image and writing a new supervisor config based on the one in this repository, and adding my configuration for celery, but it would be really nice if the current version preemptively included additional supervisor configuration, e.g.:
```
[include]
files = /etc/supervisor/conf.d/*.conf
```

(taken from an idea here: https://blog.trifork.com/2014/03/11/using-supervisor-with-docker-to-manage-processes-supporting-image-inheritance/).  That way, your image could be extended, and any additional supervisor programs could be configured separately yet still run in the same container, without the need to duplicate and overwrite the existing config file.

**Comment by tiangolo** [comment]
I use Celery all the time. It's a lot better to have additional containers for that, to have more separation of concerns.

Still, it's very common to want both containers to share a lot of code. Although not necessarily all the containers need to have all the dependencies installed in them, only the ones that are actually used.

That's way I built this: https://github.com/tiangolo/full-stack

It has all the integration and configurations needed to have independent Celery workers, in the same stack, in their own containers, that only require their dependencies but share and use almost all the base code (DB models, utils, etc).

Check that out, is as simple as:

```bash
pip install cookiecutter
cookiecutter https://github.com/tiangolo/full-stack
```

And there you have a full new project generated, and you can see how everything is configured and copy everything you need.

**Comment by guygriffiths** [comment]
Excellent thanks.  It may still be a useful feature to have the ability to start more supervisor services in the same image, but that's your call - I will use the approach you suggested.

**Comment by tiangolo** [comment]
Ok, cool. Thanks for the suggestion.

**Comment by tiangolo** [comment]
I assume you were able to solve your problem and I will close this issue now. But feel free to post more comments here if you want to re-open it or continue the conversation.

**Comment by ArtemBernatskyy** [comment]
There is no need for additional configurations, you can set up celery as easy as
- add file `celery_supervisord.conf` with 
```
[program:celery]
directory=/app
command=/usr/local/bin/celery -A your_app_name worker -l INFO --pool=solo
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

```

- modify `prestart.sh` to 

```
#! /usr/bin/env bash

# Let the DB start
sleep 10;
# Run migrations
/usr/local/bin/python manage.py migrate
# Collect static files
mkdir /app/static
/usr/local/bin/python manage.py collectstatic --noinput

# add celery config into supervisord (it will be run via supervisor later)
cp celery_supervisord.conf /etc/supervisor/conf.d
```

There is a problem with this approach - it's hard to scale celery worker this way :(
But for testing purposes (in CI pipeline) this is more than enough.
