### ISSUE TITLE
invalid cheaper value: must be lower than processes

### ISSUE THREAD

**Issue by aclowkey** [tiangolo/uwsgi-nginx-docker#34]
I'm using a custom `uwsgi.ini` file. And when I run it on this flask version of the image I'm getting:
>invalid cheaper value: must be lower than processes
> ...
> root@46f39eb48cf2:/opt/app# printenv | grep UWSGI
> UWSGI_CHEAPER=2
> UWSGI_PROCESSES=10

**Comment by aclowkey** [comment]
My uwsgi had processes=1, and the default is cheaper=2.
So I geuss this is the cause. Changing my uwsgi cheaper=0 solved this.

**Comment by tiangolo** [comment]
Do you have a public repo that I can use to reproduce the issue?

**Comment by tiangolo** [comment]
I assume you were able to solve your problem and I'll close this issue now. But feel free to add more comments or let me know if you think it should be re-opened.
