### ISSUE TITLE
Overriding NGINX conf?

### ISSUE THREAD

**Issue by aclowkey** [tiangolo/uwsgi-nginx-docker#36]
I want to add my custom nginx.conf. Is it possible with this image?

**Comment by desaintmartin** [comment]
Hello,
There are three solutions:
1/ Overwrite the default nginx configuration (This image is using the default nginx configuration from the official package with a few lines added at https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/Dockerfile#L107):
`COPY nginx.conf.template /etc/nginx/nginx.conf`
2/ Extend the nginx configuration (the default configuration includes every file in /etc/nginx/conf.d/*.conf:
`COPY nginx_custom.conf.template /etc/nginx/conf.d/000_nginx_wiremind.conf`
3/ Overwrite the custom nginx configuration set by the image (see https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/nginx.conf)

Personally, what I do is 1 and 2, but I guess it depend of your needs and style. :)

**Comment by aclowkey** [comment]
Step 3 appeals the most, but not sure how to do it.
I copied my nginx.conf, then moved it to the place of the custom but when I look at it it didn't changed. `RUN mv nginx.conf /etc/nginx/conf.d/nginx.conf
`
```
$ docker exec keen_dijkstra cat /etc/nginx/conf.d/nginx.conf                              
server {
    listen 80;
    location / {
        try_files $uri @app;
    }
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }
    location /static {
        alias /app/static;
    }
}

```

**Comment by desaintmartin** [comment]
Is that a Flask app? You may want to use or adapt https://github.com/tiangolo/uwsgi-nginx-flask-docker/

See how it is done in https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/a78e4f6a598ee6a115102b9dc32325c6e082b3f4/python2.7-alpine3.7/entrypoint.sh#L35 (although a simple `COPY` in the Dockerfile would work as well).

**Comment by aclowkey** [comment]
I am using that image, I thought it will be the no different than here. 
COPY didn't work..Original file remains..

**Comment by tiangolo** [comment]
First, thanks @desaintmartin for all your help here :+1: :clap: :smile: 

@aclowkey do you have a public repo showing the issue? If you set one up, with the config file that you want to have and the way that you are now trying to do it, maybe I could take a look and try to spot what's happening.

**Comment by desaintmartin** [comment]
@tiangolo you're welcome, I use heavily this project, so it's my way to help!

**Comment by tiangolo** [comment]
I just added a lot of tests to all the images, configurations and env vars, to be able to refactor the implementation without breaking anything.

I'm thinking about adding the possibility to provide a custom `/app/nginx.conf` file directly and use that instead of modifying/generating one. Would that solve your problem?

**Comment by tiangolo** [comment]
I just finished a big refactor of the image to be able to add this feature.

You can now add your own custom `/app/nginx.conf`, and it will be used instead of the generated done.

Check the section in the docs here: https://github.com/tiangolo/uwsgi-nginx-docker#overriding-nginx-configuration-completely

**Comment by tiangolo** [comment]
As there were no more comments, I'll assume this issue is now solved with those new options. I'll close it now, but feel free to add more comments or create new issues.
