### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by andrii1812** [tiangolo/uwsgi-nginx-docker#37]
Hi! I tried to build [this](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6-alpine3.7/Dockerfile) (python3.6-alpine3.7) dockerfile, because now I have poor Internet connection and can't pull it, and got an error while running gpg:

```
Fetching GPG key B0F4253373F8F6F510D42178520A9993A1C052F8 from ha.pool.sks-keyservers.net
gpg: keybox '/tmp/tmp.EoBIOd/pubring.kbx' created
gpg: keyserver receive failed: Address not available
Fetching GPG key B0F4253373F8F6F510D42178520A9993A1C052F8 from hkp://keyserver.ubuntu.com:80
gpg: key 520A9993A1C052F8: 6 signatures not checked due to missing keys
gpg: /tmp/tmp.EoBIOd/trustdb.gpg: trustdb created
gpg: key 520A9993A1C052F8: public key "Maxim Dounin <mdounin@mdounin.ru>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Tue Dec 26 16:02:14 2017 UTC
gpg:                using RSA key 520A9993A1C052F8
gpg: Good signature from "Maxim Dounin <mdounin@mdounin.ru>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B0F4 2533 73F8 F6F5 10D4  2178 520A 9993 A1C0 52F8
rm: can't remove '/tmp/tmp.EoBIOd/S.gpg-agent.extra': No such file or directory
rm: can't remove '/tmp/tmp.EoBIOd/S.gpg-agent.ssh': No such file or directory
```

Maybe someone knows how to fix this?
Thanks

**Comment by tiangolo** [comment]
I've seen GPG key import errors frequently because they depend on external servers that provide them, and sometimes they are down. It has happened to me many times, even with Debian based images. 

Could your please try again? Or let me know if you were able to fix it. :smile:

**Comment by tiangolo** [comment]
@andrii1812 there were recent updates to the Alpine images, several things changed underneath (although functionality should be the same). Some of those could be the ones causing your issue. 

Could you please try again with a fresh version of the image ( `docker pull tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7` )  and let me know how it goes?

**Comment by andrii1812** [comment]
Yes, I tried to build it and everything is fine now. Closing.

**Comment by tiangolo** [comment]
I'm glad you solved it, thanks for reporting back.
