### ISSUE TITLE
build failed : uwsgi-nginx-docker/python3.6/Dockerfile

### ISSUE THREAD

**Issue by ParkDyel** [tiangolo/uwsgi-nginx-docker#38]
build with docker-compose up -d

Step 13/27 : COPY uwsgi.ini /etc/uwsgi/
ERROR: Service 'api-server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder834430273/uwsgi.ini: no such file or directory

What did I do wrong?

**Comment by desaintmartin** [comment]
Are you in the uwsgi-nginx-docker/python3.6 directory? It looks like it can't find uwsgi.ini, but it exists in this directory.

**Comment by ParkDyel** [comment]
COPY A B 

command COPY A (in host system) to b (in docker system)?

**Comment by ParkDyel** [comment]
Aaa I have misunderstood about docker-compose. I want to erase this issue.
