### ISSUE TITLE
gettext-base and ca-certificates

### ISSUE THREAD

**Issue by sjbrown** [tiangolo/uwsgi-nginx-docker#4]
Hi, please forgive my ignorance, I'm lookin at this `RUN` line:
https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python2.7/Dockerfile#L13

My question is, are gettext-base and ca-certificates necessary?  I like to keep my Docker images as minimal as possible and only add packages if they'll be used.

Thank you for your work.  Reading through this project is helping me a lot.

**Comment by tiangolo** [comment]
The contents from [line 8](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python2.7/Dockerfile#L8) to [line 18](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python2.7/Dockerfile#L18) are just copied from the official [Nginx Image](https://hub.docker.com/_/nginx/) (from a previous version).

This image is basically a mix between the images for `python` and `nginx` with additional packages (`supervisor`, `uwsgi`...).

I just tried to keep it as close to the original (Nginx) base image as possible, modifying as little as I could. I'm not completely sure which cases would and woudln't work. I think you can copy the `Dockerfile`, remove things and test if it works for your specific use case.

As a side note, I just noticed that [the latest Nginx official image has a lot more packages installed](https://github.com/nginxinc/docker-nginx/blob/master/mainline/jessie/Dockerfile)...

**Comment by sjbrown** [comment]
Thanks for explaining that.

If you're curious, I was able to make a Dockerfile that worked without using the Nginx repository, it just uses the standard Debian Nginx:
https://github.com/sjbrown/misc_work/blob/master/Dockerfile.flask

**Comment by tiangolo** [comment]
Cool! 
I'm glad you were able to achieve what you wanted :tada: 

I will then close this issue now.
