### ISSUE TITLE
uwsgi reporting "no request plugin is loaded"

### ISSUE THREAD

**Issue by kraigb** [tiangolo/uwsgi-nginx-docker#40]
I'm trying to get a Django app working with uwsgi-nginx-docker as the base image. I can't get any response from the app, however, and uwsgi gives this warning:

!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
no request plugin is loaded, you will not be able to manage requests.
you may need to install the package for your language of choice, or simply load it with --plugin.
!!!!!!!!!!! END OF WARNING !!!!!!!!!!

I can see from the Dockerfile that the image does a "RUN apk add --no-cache uwsgi-python", and that python3_plugin.so is in /usr/lib/uwsgi. Why isn't uwsgi picking it up? I'm curious why it's not in /usr/lib/uwsgi/plugins where I've normally seen it.

Thanks for any ideas on this one.

**Comment by kraigb** [comment]
Closing--I had a few extra things in uwsgi.ini and was trying to run it explicitly, rather than letting the image run its start.sh.

**Comment by tiangolo** [comment]
I'm glad you solved your problem :+1: 

Nice Python pic BTW.

**Comment by kraigb** [comment]
I had that pic taken at Pycon 2018; there was a photographer in the Microsoft booth, which I was helping to staff, who was taking free and fun photos of attendees. I took advantage of a quite moment on the floor to have some fun myself. :)

**Comment by tiangolo** [comment]
Hehe cool!
