### ISSUE TITLE
Support running as a non-root user

### ISSUE THREAD

**Issue by FireDrunk** [tiangolo/uwsgi-nginx-docker#41]
Since running containers under root is _bad_ perhaps support for running as a different user is useful?

**Comment by tiangolo** [comment]
> running containers under root is bad

According to whom? I'm sorry, but although it has been stated before, I haven't been able to find an actual reason *why* is that idea. I have only seen references to blog posts from people that clearly don't seem to know how containers work. With very contrived examples as mounting a privileged directory as a volume inside an untrusted container (doing that would be the actual first issue).

Nevertheless, of course, you can do it. All the necessary steps have to be performed on your side, though. As you have to make sure your files belong to the user you are designating, and you have to decide which user are you going to use inside the container, and create it outside too. And make sure that the `UID`s match. Or make sure that you update all your code / asset files inside the container to match the owner you designated, maybe extending the entrypoint. 

It can't be done at the image level as it would have to impose all the constraints and steps that would be required to developers. And I don't really see a reason why. 

But you can easily implement all those steps on your side, for your particular application.

**Comment by FireDrunk** [comment]
Ok, thanks.
