### ISSUE TITLE
Maybe you should put a # there

### ISSUE THREAD

**Issue by huooyk** [tiangolo/uwsgi-nginx-docker#46]
https://github.com/tiangolo/uwsgi-nginx-docker/blob/7b27b4435d076fb5894fdb09ea271a0728ae4c8e/python3.6-alpine3.8/Dockerfile#L178

**Comment by tiangolo** [comment]
Yep. Thanks. I just updated it and some of the other tags that had the same issue while adding testing.

I'll close this now, but feel free to re-open or add new issues.
