### ISSUE TITLE
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)

### ISSUE THREAD

**Issue by bobmayuze** [tiangolo/uwsgi-nginx-docker#53]
On tiangolo/uwsgi-nginx:python3.5, when I am trying to start the container from this images, it tells me 

nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)

**Comment by tiangolo** [comment]
Sorry for the delay.

That means you already have something in your machine listening on port 80, maybe another container or another application. To check, open http://127.0.0.1 and see what's running there.

**Comment by tiangolo** [comment]
Thanks for coming back and closing the issue.
