### ISSUE TITLE
how to run smth before docker will start?

### ISSUE THREAD

**Issue by PankivAndrew** [tiangolo/uwsgi-nginx-docker#57]
It will be good to have smth like prestart.sh in uwsgi-nginx-flask-docker

**Comment by tiangolo** [comment]
Yep, I'm planning on implementing it.

**Comment by tiangolo** [comment]
It is now available in this image, the new docs are here: https://github.com/tiangolo/uwsgi-nginx-docker#custom-appprestartsh :tada:

**Comment by tiangolo** [comment]
I'll close this issue now, but feel free to add more comments or create new issues.
