### ISSUE TITLE
Unable to locate package gnupg1

### ISSUE THREAD

**Issue by saurabhbh21** [tiangolo/uwsgi-nginx-docker#62]
I was trying to build the docker image of uwsgi-nginx-docker on top of the base image containing Ubuntu-16.04 & Python3.5.2. 
I was getting an error **E: Unable to locate package gnupg1** 
But when I run the corresponding command in my local system, **gnupg1** gets installed.

What should I do to?

**Comment by tiangolo** [comment]
The Docker container doesn't have the same environment as your local machine, so it wouldn't have the same packages installed.

I would suggest you first check the tutorials on Docker: https://docs.docker.com/get-started/overview/ to learn how it all works, as that would be a problem specific to Docker and understanding what's actually happening underneath, not something specific to this image.

Good luck! :nerd_face: :memo:
