### ISSUE TITLE
Are there any plans to create a Dockerfile for Debian Buster?

### ISSUE THREAD

**Issue by manuel-castro** [tiangolo/uwsgi-nginx-docker#64]
Hi,

I was wondering, now that Buster is the latest stable distribution, if there were any plans to create a  Dockerfile for Debian Buster. Would it possibly be as simple as just changing the initial FROM line/base image?

Thanks

**Comment by tiangolo** [comment]
Yep. All the latest images are now based on Buster, including a new one for Python 3.8. :rocket: :tada:
