### ISSUE TITLE
Are UWSGI_CHEAPER and UWSGI_PROCESSES being used?

### ISSUE THREAD

**Issue by shawnwall** [tiangolo/uwsgi-nginx-docker#67]
I see the following in Dockerfile:

```
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY uwsgi.ini /etc/uwsgi/
...
# By default, run 2 processes
ENV UWSGI_CHEAPER 2
# By default, when on demand, run up to 16 processes
ENV UWSGI_PROCESSES 16
```

...but so far can't find these ENV vars being referenced anywhere. Perhaps its just a misunderstanding on my part.  I don't see them being used in the uwsgi script line in the supervisord conf either. Perhaps UWSGI itself magically looks for these variables, but I didn't see that document in the UWSGI docs either.

**Comment by machine424** [comment]
According to the doc, uWSGI supports passing options as env variables: https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables.

If I were you, I'd not use the term "magically" to avoid making real "Magic variables": https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#magic-variables upset.

uWSGI can be configurable in A LOT of ways, making it difficult to identify the final value of an option before starting/restarting the server.

**Comment by tiangolo** [comment]
Thanks for the help here @machine424 !

Yeah, uWSGI gets quite difficult to handle with so many points of configuration...

Now I also prefer this image with FastAPI: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker

It's much simpler to configure, understand, and debug (apart from much better performance).
