### ISSUE TITLE
entrypoint.sh permission error on docker run

### ISSUE THREAD

**Issue by cleiton-willians** [tiangolo/uwsgi-nginx-docker#7]
When i try to run my image (which i use this one as base) i get the following error:

docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/entrypoint.sh\\\": permission denied\"\n".

I tried to add "RUN chmod +x /entrypoint.sh" since some people said this solved there problem in other projects, but that didn't work for me. 

My docker file:
FROM tiangolo/uwsgi-nginx:python2.7
COPY configs/nginx.conf /etc/nginx/conf.d/

# Copy sample app
COPY ./ /app

#install requirements
RUN pip install -r requirements.txt

ENV PRODUCTION_ENV 1

EXPOSE 5050

**Comment by tiangolo** [comment]
Yes! I was in the middle of several fixes and improvements.

And there was a window of time (a couple hours?) in where that bug could have happened. But it should be fixed now.

I'm actually impressed by the fact that you caught the bug in that short period of time! :sweat_smile: 

Please check again and let me know if it is working now.

---

To check out the new improvements, features and changes go to the releases page: https://github.com/tiangolo/uwsgi-nginx-docker/releases :tada:

**Comment by tiangolo** [comment]
As this issue is quite old, I'll assume your problem is solved.
