### ISSUE TITLE
Slim base image

### ISSUE THREAD

**Issue by BubaVV** [tiangolo/uwsgi-nginx-docker#72]
Do you plan to use slim base image? Currently, python3.6 image takes 960 Mb, but if build it from python:3.6-slim-stretch base image, image results in only 431 Mb - more than twice smaller. Further compacting is possible if remove build-essentials after uwsgi install - it can cut some hundred Mb more

**Comment by tiangolo** [comment]
The problem is that many Python packages depend on being built at installation, so the slim versions are only an option when you are completely sure that you are not installing packages that need building, so it's not very generalizable.
