### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by Uninen** [tiangolo/uwsgi-nginx-docker#73]
Would love to see a python 3.8 version of this project :)

These are super nice images, they pair awesomely with traefik 👍

**Comment by CodeForcer** [comment]
Your docker images are great @tiangolo, please create a Python 3.8 version as it's much needed by a lot of people!

**Comment by neveldo** [comment]
+1, it would be great :) By the way, this is a great and usefull project @tiangolo , thank you, thank you !!

**Comment by pupattan** [comment]
Is it possible to get Python 3.8 with Alpine ?

**Comment by tiangolo** [comment]
Hey all! I'm glad it's being helpful to you. :tada: 

Yes, I just added a new image for Python 3.8, and a new Alpine with Python 3.8. :rocket: :cake:

**Comment by neveldo** [comment]
Hi ! What a great news ! Thanks a lot for your work @tiangolo , this is a very useful project !

**Comment by tiangolo** [comment]
I'm glad it's being useful! :smile: :tada:

**Comment by Uninen** [comment]
Thank You for your work @tiangolo !
