### ISSUE TITLE
Unable to run multiple container instance of this image

### ISSUE THREAD

**Issue by pupattan** [tiangolo/uwsgi-nginx-docker#80]
When i am trying to run multiple container instance with this same image i am getting the following error.

> Bind for 0.0.0.0:443 failed: port is already allocated

Is there any solution for this ?
how can we using something like nginx-proxy with this image ?

**Comment by tiangolo** [comment]
You would probably use a single frontend proxy/load balancer on top. It could also work as TLS termination proxy.

I would recommend Traefik, as it can read the labels in your containers to generate configs automatically and acquire free Let's Encrypt HTTPS certificates for you.
