### ISSUE TITLE
('IM004', "[IM004] [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by kelvin1794** [tiangolo/uwsgi-nginx-docker#88]
Hey guys,

I'm trying to leverage on this container to build my app with Django and MS SQL.

The prerequisite is of course to have the ODBC driver installed. So I did the below step in my Dockerfile:

```
RUN apt-get update && apt-get install -y ca-certificates \
    && curl -k https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl -k https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get -y install msodbcsql17 \
    && ACCEPT_EULA=Y apt-get -y install mssql-tools \
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc \
    && /bin/bash -c "source ~/.bashrc" \
    && apt-get install -y unixodbc-dev \
    && apt-get install -y libgssapi-krb5-2
```

This built the image perfectly. When I run it with Docker on my laptop, the app works fine. However, after deploying the image to Azure web app service, the below error happens.

```
('IM004', "[IM004] [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed (0) (SQLDriverConnect)")
```

Really appreciate any help from you guys.

**Comment by kelvin1794** [comment]
I finally managed to solve this problem.

The error above is because when deployed to Azure App Service, the GID that runs the app is 1000 but in `etc/passwd` there isn't that user.

So I added this into my Dockerfile and now it's working okay.

```
ARG USERNAME=finex_app_service
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
```

**Comment by tiangolo** [comment]
Thanks for coming back to close the issue! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
