### ISSUE TITLE
Outdated link for "You can see the third-party benchmarks here" ?

### ISSUE THREAD

**Issue by bomalabs** [tiangolo/uwsgi-nginx-docker#89]
Thanks a TON for this wonderful project! Just a minor issue in the docker hub page [https://hub.docker.com/r/tiangolo/uwsgi-nginx/](url), the link for "You can see the third-party benchmarks here" leads to VB and F# frameworks. 

![outdated-link](https://user-images.githubusercontent.com/48353394/93601328-9deac780-f9f3-11ea-8bb0-8fc8d167d987.png)

You probably mean this: [https://www.techempower.com/benchmarks/#section=test&runid=a979de55-980d-4721-a46f-77298b3f3923&hw=ph&test=fortune&l=z8kflr-v&a=2](url)

Or even better, this:
[https://www.techempower.com/benchmarks/#section=test&runid=a979de55-980d-4721-a46f-77298b3f3923&hw=ph&test=query&l=z8kflr-v&a=2](url)

**Comment by tiangolo** [comment]
Good catch, thanks! :coffee: 

I just fixed it in https://github.com/tiangolo/uwsgi-nginx-docker/pull/96
