### ISSUE TITLE
How change run user to another

### ISSUE THREAD

**Issue by alizowghi** [tiangolo/uwsgi-nginx-docker#9]
Hi
How can I change run user to my custom user?

**Comment by tiangolo** [comment]
In your `Dockerfile`, like:

```Dockerfile
FROM tiangolo/uwsgi-nginx:latest

COPY ./app /app

USER appuser
```

But that is not specific of this project. Here's the official documentation from Docker: https://docs.docker.com/engine/reference/builder/#user

**Comment by tiangolo** [comment]
As this issue is quite old, I'll assume your problem is solved and close it.
