### ISSUE TITLE
How do I use your image to build a Django service

### ISSUE THREAD

**Issue by mkg666** [tiangolo/uwsgi-nginx-docker#91]
I'm sorry to bother you, but there were various problems when using your mirror to build Django. Do you have a demo of django? Thank you again for your open source

**Comment by davidshumway** [comment]
Agree. Demos would be nice. Did you find any?

**Comment by tiangolo** [comment]
I'm currently not using Django, and I don't have a demo, but Microsoft has a tutorial using this image :nerd_face: https://docs.microsoft.com/en-us/azure/app-service/tutorial-custom-container

That might be useful. :crossed_fingers:

**Comment by karlhedins** [comment]
Made a small example with [uwsgi-nginx-docker](https://github.com/tiangolo/uwsgi-nginx-docker) configured with Django:
https://github.com/karlhedins/uwsgi-nginx-django-docker
