### ISSUE TITLE
What is the recommended way to modify conf.d?

### ISSUE THREAD

**Issue by MareoRaft** [tiangolo/uwsgi-nginx-docker#93]
I would like to modify `conf.d` in order to allow CORS for my other server.

I see that there are two such files:
`/etc/nginx/conf.d/nginx.conf`
`/etc/nginx/nginx.conf`

Trying to replace the former with a `COPY nginx.conf /etc/nginx/conf.d/.` is causing unexpected behavior.  Adding a `conf.d` to `/app/`, on the other hand, is causing BOTH of the conf.d files listed above to be replaced, causing nginx to crash with

    nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/nginx.conf:1

What is the recommended way to do this?

**Comment by sharmautkarsh31** [comment]
Did you find a solution?

**Comment by MareoRaft** [comment]
I'm sorry, this was a long time ago and I no longer remember.
