### ISSUE TITLE
Environment variable NGINX_MAX_UPLOAD is not working

### ISSUE THREAD

**Issue by sujeetkv** [tiangolo/uwsgi-nginx-docker#95]
I have set `ENV NGINX_MAX_UPLOAD 8m` in my Dockerfile but it seems not working because I am not able to upload more than 1MB content. NGINX rejects request saying - Request Entity Too Large.

**Comment by tiangolo** [comment]
Hey :wave: 

If you are still having errors, please create a minimal self-contained example replicating the issue so that I can check it here. Probably just a minimal `Dockerfile` and a minimal Python app that show the error.
