### ISSUE TITLE
how to read nginx error.log?

### ISSUE THREAD

**Issue by lidyum** [tiangolo/uwsgi-nginx-docker#98]
`docker exec -it [container_name] bash`
in my docker container;

`cd /var/log/nginx`

in folder;
**access.log  error.log**

`nano error.log`

**error.log is not a normal file**

![cmd](https://user-images.githubusercontent.com/12731789/108844780-9906f100-75ed-11eb-9dc5-ef05e2f949e5.jpg)

**Comment by t-tagami** [comment]
You can do it with this command.
`docker logs [container_name]`

**Comment by tiangolo** [comment]
Thanks for the help here @t-tagami ! 👏  🙇 

Thanks for coming back and closing the issue @lidyum 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
